# Background and foreground colors
background = #010101
foreground = #E4E5E7

# Standard colors
palette = 0=#010101
palette = 1=#ae6444
palette = 2=#f9a916
palette = 3=#cf943f
palette = 4=#87a3cd
palette = 5=#a1bbed
palette = 6=#657da9
palette = 7=#E4E5E7

# Bright colors
palette = 8=#5c5a54
palette = 9=#da865c
palette = 10=#ffaf00
palette = 11=#fbba45
palette = 12=#aac8fe
palette = 13=#a3c5ff
palette = 14=#87a0d9
palette = 15=#dfebff
