$color = rgba(1, 1, 1, 1)
$inner_color = rgba(1, 1, 1, 0.66)
$outer_color = rgba(161, 187, 237, 1)
$font_color = rgba(228, 229, 231, 1)
$placeholder_color = rgba(228, 229, 231, 0.7)
$check_color = rgba(101, 125, 169, 1)
